[package]
name = "heapuse-tests"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dev-dependencies]
heapuse = { path = "../heapuse" }
heapuse-derive = { path = "../heapuse-derive" }

trybuild = "1.0"
snapbox = { version = "0.5" }
