name: Publish

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: cargo version && rustc -V
      - run: cargo build --all-features
      - run: cargo publish -p heapsz-derive
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.HEAPSZ_RELEASE_TOKEN }}
      - run: cargo publish -p heapsz
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.HEAPSZ_RELEASE_TOKEN }}
