[package]
name = "heapuse"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

[dev-dependencies]
heapuse-derive = { path = "../heapuse-derive" }
trybuild = "1.0"
snapbox = "0.5"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
